### ISSUE TITLE
Check how resource version works

### ISSUE THREAD

**Issue by Prytu** [Prytu/risk-advisor#29]
Check if resource version is the same for all resources (i.e pods, nodes etc). Maybe do some more research and find out if there is something interesting we should know.

**Comment by jackmax** [comment]
According to documentation, the resource version is a value used for checking if the state an object has changed. The systems are not supposed to change it or assume anything about its contents (including that it is the same for different types of resources).
https://github.com/kubernetes/kubernetes/blob/release-1.4/docs/devel/api-conventions.md#concurrency-control-and-consistency

In reality it is an integer passed as string, seems to be global for the entire system and incremented whenever the state of the system changes.
