### ISSUE TITLE
Research on Google/Kubernetes CI (Mik mentioned Jenkins)

### ISSUE THREAD

**Issue by GraczykowskiMichal** [Prytu/risk-advisor#57]

**Comment by GraczykowskiMichal** [comment]
Please present results here or in Wiki

**Comment by pposkrobko** [comment]
I think this is what Mik meant: https://github.com/kubernetes/test-infra 

However, I don't see an easy way how to 1) access test infrastructure 2) create own tests, especially for our purpose.  There is a readme saying how to work with Jenkins jobs on test-infra repo: https://github.com/kubernetes/test-infra/blob/master/jenkins/README.md My impression is that it's not supposed for testing additional modules as ours, but rather for the Kubernetes core.

I was unable to find an easy, do-what-you-want access to some set-up Kubernetes infrastructure to replace our testing using one-node minikube cluster with something closer to real usage scenario.

I also took a look at non-core Kuberenetes modules from contrib repo (https://github.com/kubernetes/contrib) and I didn't see any project using test-infra, having defined Jenkins test jobs etc. 

I think we need to ask Mik whether test-infra repo is exactly what he meant + if so, verify that I didn't omit something important for us inside it.

If we're unable to use some public Kubernetes test infrastructure, we'll need to stick with providing it on our own, like creating cluster for test purposes on Google Cloud or maybe we can do more extensive testing using minikube.
