### ISSUE TITLE
Add watcher support to proxy

### ISSUE THREAD

**Issue by Prytu** [Prytu/risk-advisor#7]
At the moment we just ignore watchers set on pods by scheduler.
Check how hard it will be to support them, and implement it if its not too hard.

**Comment by jackmax** [comment]
### Issue
When a simple proxy for watch requests was implemented, the scheduler kept asking the API server for an old resource version that no longer existed. This caused the API server to return an error:
`"{"type":"ERROR","object":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"too old resource version: 1 (3)","reason":"Gone","code":410}}"`

### Reason
The scheduler stores the current resource version internally and **updates it only when a request is successful**. Normally, performing a `GET /api/v1/pods` request provides the latest resource version, and watchers work correctly.

Currently, this request returns one of our PodLists, which have a resource version of `"1"` hardcoded into them, resulting in the error.

### Proposed fix
* Modify `handleGetPods` to communicate with the API server and retrieve the latest resource version. Use it for communicating with the API server.
* Keep a resource version internally in our proxy, increment it whenever changes to the state (e.g. advise requests) are made. Use it for communicating with the scheduler.
* Modify watch requests coming from scheduler to change the requested resource version.
